Repository CECOM-CAU/CECOM_Web, pull requests merged in 2024-01, with the labels that each got.

#4 [DOC] Project Convention 구성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  Conventions.md
Labels: doc

#6 [DEV] header 1차 구현
  public/HeaderLogo.svg
  src/app/_components/NavBar.tsx
  src/app/_components/NavBarDesktop.tsx
  src/app/_components/NavButton.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: dev

#7 [FIX] NavBar 관련 수정 및 코드 정리
  src/app/_components/NavBar.tsx
  src/app/_components/NavBar/NavBar.tsx
  src/app/_components/NavBar/NavBarDesktop.tsx
  src/app/_components/NavBar/NavButton.tsx
  src/app/_components/NavBarDesktop.tsx
  src/app/_components/NavButton.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: fix
