Repository CECOM-CAU/CECOM_Web, pull requests merged in 2024-02, with the labels that each got.

#10 [DEV] Default Style 관련 설정
  src/app/favicon.ico
  src/app/globals.css
  src/fonts/GmarketSansBold.otf
  src/fonts/GmarketSansLight.otf
  src/fonts/GmarketSansMedium.otf
  tailwind.config.ts
Labels: dev

#11 [DEV] NavBar BTN 클릭 시 처리 구현
  src/app/_components/NavBar/NavBar.tsx
  src/app/_components/NavBar/NavBarDesktop.tsx
  src/app/_components/NavBar/NavButton.tsx
Labels: dev

#12 [DEV] pagetitle props 구현
  package-lock.json
  package.json
  public/Thingsphoto.jpg
  public/Titlelogo.png
  src/app/_components/PageTitle.tsx
  src/app/things/_components/menubar.tsx
  src/app/things/_components/newbar.tsx
  src/app/things/_components/page.tsx
  src/app/things/page.tsx
Labels: dev

#17 [DEV] fixed title display
  src/app/_components/PageTitle.tsx
Labels: fix

#19 [DEV] resolve Hydration failed
  src/app/_components/NavBar/NavButton.tsx
Labels: fix

#21 [DEV] NavBTN recurit 버튼 추가
  src/app/_components/NavBar/NavBarDesktop.tsx
  src/app/_components/NavBar/RecruitBTN.tsx
Labels: dev

#22 [DEV] update pagetitle margin-top
  src/app/_components/PageTitle.tsx
Labels: dev

#23 [DEV] 데이터 Interface 구성
  src/utils/DummyData.ts
  src/utils/Interfaces.ts
Labels: dev

#24 [dev] Things update
  src/app/things/_components/menubar.tsx
  src/app/things/_components/newbar.tsx
  src/app/things/_components/page.tsx
  src/app/things/page.tsx
Labels: dev

#27 [DEV] activities 페이지 1차 구현
  src/app/_components/NavBar/NavButton.tsx
  src/app/activities/_components/ActivityCard.tsx
  src/app/activities/_components/MenuBTN.tsx
  src/app/activities/page.tsx
Labels: dev

#28 [DEV] header 로고 위치 변경
  src/app/_components/NavBar/NavBarDesktop.tsx
Labels: dev

#29 [DEV] page title 위치 변경
  src/app/_components/PageTitle.tsx
Labels: fix

#33 [FIX] 데이터 Interface 개선
  src/utils/DummyData.ts
  src/utils/Interfaces.ts
Labels: fix

#34 [DEV] BE Firestore 관련 Util 구성
  .gitignore
  package-lock.json
  package.json
  src/utils/FirebaseUtil.ts
Labels: dev

#36 [DEV] BE 기본 API 라우팅 구성
  src/app/api/activities/getActivitiesData/[id]/route.ts
  src/app/api/activities/getActivitiesList/route.ts
  src/app/api/members/getMembersList/route.ts
  src/app/api/things/getThingsList/route.ts
Labels: dev

#38 [DEV] Docker 배포 및 Jenkins CI/CD 적용
  Dockerfile
  Jenkinsfile
  next.config.js
  src/app/activities/page.tsx
Labels: dev

#41 [DEV] 헤더 수정 사항
  src/app/_components/NavBar/NavBar.tsx
  src/app/_components/NavBar/NavBarDesktop.tsx
Labels: dev

#42 [DEV] Activity card 애니메이션 구현
  src/app/activities/_components/ActivityCard.tsx
  src/app/activities/_components/ActivityCardBack.tsx
  src/app/activities/_components/ActivityCardFront.tsx
  src/app/activities/page.tsx
Labels: dev

#43 [FIX] 데이터 Interface 및 더미데이터 개선사항 반영
  src/app/activities/_components/ActivityCardBack.tsx
  src/app/activities/_components/ActivityCardFront.tsx
  src/app/activities/page.tsx
  src/utils/DummyData.ts
  src/utils/Interfaces.ts
Labels: fix

#45 [DEV] BE Members API 구현
  src/app/api/members/getMembersList/route.ts
  src/utils/DummyData.ts
  src/utils/FirebaseUtil.ts
  src/utils/Interfaces.ts
Labels: dev

#47 [DEV] Home 화면 1차 구현
  src/app/_components/mainPage/DoLeft.tsx
  src/app/_components/mainPage/DoRight.tsx
  src/app/_components/mainPage/MainLogo.tsx
  src/app/_components/mainPage/WhatWeDo.tsx
  src/app/_components/mainPage/Who.tsx
  src/app/page.tsx
Labels: dev

#49 [DEV] 홈 화면 이미지 이미지링크로 대체
  src/app/_components/mainPage/WhatWeDo.tsx
Labels: dev

#51 [DEV] activity card 구조 변경
  src/app/activities/_components/ActivityCard.tsx
  src/app/activities/_components/ActivityCardBack.tsx
  src/app/activities/page.tsx
Labels: dev

#53 [DEV] 홈 화면 plus 아이콘 수정
  package.json
  src/app/_components/mainPage/Who.tsx
Labels: dev

#54 [FIX]Things 페이지 수정
  src/app/things/_components/page.tsx
  src/app/things/page.tsx
Labels: dev

#56 [DEV] footer 구현
  src/app/_components/Footer/Footer.tsx
  src/app/_components/Footer/FooterDesktop.tsx
  src/app/layout.tsx
Labels: dev

#57 [DEV] header button 호버 시 배경 색 변경
  src/app/_components/NavBar/NavButton.tsx
Labels: dev

#59 [DEV] home 화면 슬로건 수정
  src/app/_components/mainPage/MainLogo.tsx
  src/app/page.tsx
Labels: dev

#61 [DEV] activity card tag style수정
  src/app/activities/_components/ActivityCardFront.tsx
  src/app/activities/page.tsx
Labels: dev

#63 [FIX] 데이터 Interface 이슈 추가해결
  src/utils/DummyData.ts
  src/utils/Interfaces.ts
Labels: fix

#64 [FIX] 데이터 Interface 찐찐막 추가해결
  src/utils/DummyData.ts
  src/utils/Interfaces.ts
Labels: fix

#67 [DEV] BE Activity List API 구현
  package-lock.json
  package.json
  src/app/api/activities/getActivitiesList/route.ts
  src/utils/FirebaseUtil.ts
Labels: fix, dev

#68 [FIX] members 페이지 로고 수정
  public/MemberBack.jpg
  public/Memberimg.jpg
  src/app/members/_components/Backcard.tsx
  src/app/members/_components/membercard.tsx
Labels: dev

#71 [FIX] footer 랜더링 오류 수정
  src/app/_components/Footer/FooterDesktop.tsx
  src/app/layout.tsx
Labels: fix

#72 [FIX] members 페이지 수정
  src/app/members/_components/Backcard.tsx
  src/app/members/page.tsx
  src/utils/DummyData.ts
Labels: dev

#75 [FIX] Filesystem 접근불가 이슈 해결
  src/app/api/_utils/FileUtil.ts
  src/utils/FirebaseUtil.ts
Labels: fix

#73 [FIX] things 페이지 메뉴바 수정
  src/app/things/_components/menubar.tsx
  src/app/things/_components/page.tsx
Labels: dev

#76 [DEV] activity detail 구현
  public/GithubLogo.png
  public/InstagramLogo.png
  src/app/activities/[id]/_component/Bubble.tsx
  src/app/activities/[id]/_component/Member.tsx
  src/app/activities/[id]/_component/MemberInfo.tsx
  src/app/activities/[id]/_component/PhotoCarousel.tsx
  src/app/activities/[id]/_component/Role.tsx
  src/app/activities/[id]/page.tsx
  src/app/activities/_components/ActivityCardFront.tsx
  src/app/activities/_components/Tag.tsx
Labels: dev

#78 [DEV] BE Things API 구현
  src/app/api/things/getThingsList/route.ts
  src/utils/FirebaseUtil.ts
Labels: dev

#82 [FIX] 홈화면 가로 스크롤 문제 해결
  src/app/_components/mainPage/MainLogo.tsx
  src/app/page.tsx
Labels: fix

#83 [DEV] BE Filesystem 접근 AddOn Server 작업
  AddOnServer/.gitignore
  AddOnServer/package.json
  AddOnServer/src/index.ts
  AddOnServer/tsconfig.json
  Dockerfile
  package.json
  src/app/api/_utils/FileUtil.ts
  src/utils/FileUtil.ts
  src/utils/FirebaseUtil.ts
Labels: fix, dev

#85 [Fix] activity card 뒷면 멤버이름 구분자 추가
  src/app/activities/_components/ActivityCardBack.tsx
Labels: fix

#87 [FIX] BE CORS 관련 설정 변경
  src/app/api/activities/getActivitiesData/[id]/route.ts
  src/app/api/activities/getActivitiesList/route.ts
  src/app/api/members/getMembersList/route.ts
  src/app/api/things/getThingsList/route.ts
  src/utils/CorsUtil.ts
Labels: fix

#88 [DEV]members 페이지 api 연결
  package.json
  src/app/members/page.tsx
Labels: dev

#89 [DEV]things 페이지 api 연결
  package.json
  src/app/things/_components/page.tsx
  src/app/things/page.tsx
Labels: dev

#91 [DEV] activities 페이지 API 연결
  src/app/activities/_components/ActivityCard.tsx
  src/app/activities/page.tsx
Labels: dev

#98 [DEV] BE Main Image API 구현
  src/app/api/main/getMainImages/route.ts
  src/utils/FileUtil.ts
  src/utils/Interfaces.ts
Labels: dev

#97 [DEV] BE Activity Data API 구현
  src/app/api/activities/getActivitiesData/[id]/route.ts
  src/utils/FileUtil.ts
  src/utils/FirebaseUtil.ts
  src/utils/Interfaces.ts
Labels: dev

#101 [FIX] 홈 화면 수정 요청 반영
  src/app/_components/mainPage/WhatWeDo.tsx
Labels: fix

#103 [FIX] FE activities 수정 사항 반영
  src/app/activities/_components/MenuBTN.tsx
  src/app/activities/_components/Tag.tsx
Labels: fix

#93 [FIX] Navbar 버튼 오류 수정
  src/app/_components/NavBar/NavBarDesktop.tsx
Labels: fix

#109 [FIX] BE Members API 누락사항 수정
  src/utils/FirebaseUtil.ts
Labels: fix

#111 [DEV] mobile 홈 화면 2차 구현
  src/app/_components/mainPage/WhatWeDo.tsx
  src/app/_components/mainPage/desktop/DesktopHome.tsx
  src/app/_components/mainPage/desktop/DesktopMainLogo.tsx
  src/app/_components/mainPage/desktop/WhatLeft.tsx
  src/app/_components/mainPage/desktop/WhatRight.tsx
  src/app/_components/mainPage/desktop/WhatWeDo.tsx
  src/app/_components/mainPage/desktop/Who.tsx
  src/app/_components/mainPage/mobile/MobileHome.tsx
  src/app/_components/mainPage/mobile/MobileMainLogo.tsx
  src/app/_components/mainPage/mobile/MobileWhatLeft.tsx
  src/app/_components/mainPage/mobile/MobileWhatRight.tsx
  src/app/_components/mainPage/mobile/MobileWhatWeDo.tsx
  src/app/_components/mainPage/mobile/MobileWho.tsx
  src/app/page.tsx
Labels: dev

#113 [DEV] mobile activity 페이지 구현
  src/app/_components/MobilePageTitle.tsx
  src/app/_components/PageTitle.tsx
  src/app/activities/_components/ActivityCard.tsx
  src/app/activities/_components/ActivityCardBack.tsx
  src/app/activities/_components/MenuBTN.tsx
  src/app/activities/page.tsx
Labels: dev

#114 [DEV] members page card 수정 및 모바일 구현
  src/app/members/_components/Backcard.tsx
  src/app/members/_components/DeskFlip.tsx
  src/app/members/_components/MobFlip.tsx
  src/app/members/_components/projectname.tsx
  src/app/members/page.tsx
Labels: dev

#116 [FIX] BE Activity Photo 관련 카운팅 문제
  src/utils/FirebaseUtil.ts
Labels: fix

#118 [FIX] BE Members API 정렬
  src/utils/FirebaseUtil.ts
Labels: fix

#119 [DEV] members 페이지 year bar 수정 및 모바일 select bar 구현
  src/app/members/_components/Backcard.tsx
  src/app/members/_components/membercard.tsx
  src/app/members/page.tsx
Labels: dev

#121 [DEV] activity detail page 구현
  src/app/activities/[id]/_component/Member.tsx
  src/app/activities/[id]/_component/Role.tsx
  src/app/activities/[id]/_component/desktop/DesktopDetail.tsx
  src/app/activities/[id]/_component/desktop/PhotoCarousel.tsx
  src/app/activities/[id]/_component/mobile/MobileCarousel.tsx
  src/app/activities/[id]/_component/mobile/MobileDetail.tsx
  src/app/activities/[id]/page.tsx
  src/app/activities/page.tsx
Labels: dev

#122 [DEV] things 메뉴바 수정 및 모바일 구현
  src/app/activities/page.tsx
  src/app/things/_components/MobSmallBox.tsx
  src/app/things/_components/ThingMenu.tsx
  src/app/things/_components/menubar.tsx
  src/app/things/_components/page.tsx
  src/app/things/page.tsx
Labels: dev

#123 [FIX] members 페이지 card flip 수정
  src/app/members/_components/Backcard.tsx
  src/app/members/_components/DeskFlip.tsx
Labels: fix

#125 [DEV] 홈 화면 데이터 연결
  src/app/_components/mainPage/desktop/WhatWeDo.tsx
  src/app/_components/mainPage/desktop/Who.tsx
  src/app/_components/mainPage/mobile/MobileHome.tsx
  src/app/_components/mainPage/mobile/MobileWhatWeDo.tsx
Labels: dev

#127 [DEV] 홈 화면 데이터 불러오기 수정
  src/app/_components/mainPage/desktop/DesktopHome.tsx
  src/app/_components/mainPage/desktop/WhatLeft.tsx
  src/app/_components/mainPage/desktop/WhatRight.tsx
  src/app/_components/mainPage/desktop/WhatWeDo.tsx
  src/app/_components/mainPage/mobile/MobileHome.tsx
  src/app/_components/mainPage/mobile/MobileWhatLeft.tsx
  src/app/_components/mainPage/mobile/MobileWhatRight.tsx
  src/app/_components/mainPage/mobile/MobileWhatWeDo.tsx
  src/app/page.tsx
Labels: fix, dev

#132 [DEV] FE Footer 모바일UI 대응
  src/app/_components/Footer/Footer.tsx
  src/app/_components/Footer/FooterDesktop.tsx
  src/app/_components/Footer/FooterMobile.tsx
Labels: fix, dev

#135 [FIX] FE 이미지 resize 속성 추가
  src/app/activities/[id]/_component/desktop/PhotoCarousel.tsx
  src/app/activities/[id]/_component/mobile/MobileCarousel.tsx
  src/app/activities/_components/ActivityCardFront.tsx
Labels: fix

#136 [FIX] FE 모바일 what we do 에 들어가는 이미지 속성 수정
  src/app/_components/mainPage/mobile/MobileWhatLeft.tsx
  src/app/_components/mainPage/mobile/MobileWhatRight.tsx
Labels: fix

#138 [FIX] FE 모바일 헤더 CSS 수정사항
  public/Close.svg
  public/Menu.svg
  public/MobileLogo.svg
  src/app/_components/NavBar/NavBarMobile.tsx
Labels: fix

#139 [FIX] members 페이지 액티비티 이동 버튼 수정
  src/app/members/_components/Backcard.tsx
  src/app/members/_components/projectname.tsx
  src/app/members/page.tsx
Labels: fix

#140 [FIX] members 페이지 카드 수정
  src/app/members/page.tsx
Labels: fix

#145 [DEV/FIX] Activity 및 Members 기본 이미지 렌더링 적용
  public/IconFemale.png
  public/IconMale.png
  public/MemberFemale.png
  public/MemberMale.png
  src/app/activities/[id]/_component/Member.tsx
  src/app/activities/[id]/_component/Role.tsx
  src/app/members/_components/BackCard.tsx
  src/app/members/_components/DeskFlip.tsx
  src/app/members/_components/FrontCard.tsx
  src/app/members/_components/MemberProjectItem.tsx
  src/app/members/_components/MobFlip.tsx
  src/utils/FirebaseUtil.ts
  src/utils/Interfaces.ts
Labels: fix, dev

#149 [FIX] Fetching Cache 비활성화 설정 적용
  src/app/activities/[id]/page.tsx
  src/app/activities/page.tsx
  src/app/members/page.tsx
  src/app/page.tsx
  src/app/things/page.tsx
Labels: fix

#151 [FIX] FE 액티비티 아이콘 겹침 문제 및 모바일 화면 구성 수정
  src/app/activities/[id]/_component/Role.tsx
  src/app/activities/[id]/_component/mobile/MobileDetail.tsx
Labels: fix

#152 [FIX] Fetching Cache 비활성화 설정 적용
  src/app/activities/[id]/page.tsx
  src/app/activities/page.tsx
  src/app/api/activities/getActivitiesData/[id]/route.ts
  src/app/api/activities/getActivitiesList/route.ts
  src/app/api/main/getMainImages/route.ts
  src/app/api/members/getMembersList/route.ts
  src/app/api/things/getThingsList/route.ts
  src/app/members/page.tsx
  src/app/page.tsx
  src/app/things/page.tsx
Labels: fix

#154 [FIX] Recruiting Google Form 연동
  src/app/_components/NavBar/NavBarDesktop.tsx
  src/app/_components/NavBar/RecruitBTN.tsx
Labels: fix
